'---------------------------------------------------
' Preconditions:
' 1. Open a part, assembly, or drawing that has at least
'    one annotation containing text.
' 2. Select that annotation.
' 3. Open the Immediate window.
'
' Postconditions:
' 1. Changes text in annotation
'----------------------------------------------------
Option Explicit
    Dim swApp                       As SldWorks.SldWorks
    Dim swModel                     As SldWorks.ModelDoc2
    Dim swDrawing                   As SldWorks.DrawingDoc

    Dim swNote                      As SldWorks.Note
    Dim swView                      As SldWorks.View
    
    Dim ret                        As Boolean
    Dim oldText                     As String
    Dim newText                     As String

Sub main()
    Set swApp = Application.SldWorks
    Set swModel = swApp.ActiveDoc
    Set swDrawing = swModel
    swDrawing.EditTemplate
    Set swView = swDrawing.GetFirstView
    
    oldText = "change me"
    newText = "changed?"
    
    'EXTRA STUFF ---------------
    ' Verify that the document is a drawing
'    If (swModel Is Nothing) Or (swModel.GetType <> swDocDRAWING) Then
'        Exit Sub
'    End If
'    Set swDrawing = swModel
    '--------------------------
    
    Debug.Print "replace [" + oldText + "] with [" + newText + "]"
    Set swNote = swView.GetFirstNote
    While Not swNote Is Nothing
        If (swNote.GetText = oldText) Then
            Debug.Print ">found a note"
            ret = swNote.SetText(newText)
        End If
        Set swNote = swNote.GetNext
    Wend
    Debug.Print "done"
End Sub

